I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter01.rpy", line 163, in script
    hide soleil angry with dissolve
OSError: Couldn't find file 'audio.footstepsaway122(1st).mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter01.rpy", line 163, in script
    hide soleil angry with dissolve
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\ast.py", line 1459, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\display\core.py", line 2774, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\display\core.py", line 3336, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\display\core.py", line 4036, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1160, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1138, in periodic_thread_main
    periodic_pass()
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1080, in periodic_pass
    c.periodic()
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\audio\audio.py", line 517, in periodic
    topf = load(filename)
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\audio\audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\Ethan\Downloads\renpy-7.4.11-sdk\renpy\loader.py", line 804, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio.footstepsaway122(1st).mp3'.

Windows-10-10.0.19042
Ren'Py 8.0.0.22011702n
donor 1.0
Tue Jan 25 16:51:04 2022
