I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 149, in script
    jump day_2
ScriptError: could not find label 'day_2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 149, in script
    jump day_2
  File "C:\Users\prans\Downloads\Setups\renpy-7.4.10-sdk\renpy\ast.py", line 1773, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\prans\Downloads\Setups\renpy-7.4.10-sdk\renpy\script.py", line 917, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'day_2'.

Windows-10-10.0.19044
Ren'Py 8.0.0.22011701n
main 1.0
Tue Jan 18 18:41:17 2022
